# Comments made here should persist through automatic edits.
# Need help? https://github.com/Teascade/pipeswitch/blob/main/README.md#config
[general]
# keep links that dont exist in the config anymore
linger_links = false
# inotify listen config and reload when it changes
hotreload_config = true

[log]
# trace / debug / info / warn / error
level = "info"

# Default link. You may delete me!
[link.some_default_link]
in = { client = "client_1", node = "node_1" }
out = "Hello there!"
# Optional per-link config  
#  special_empty_ports = true
