name: release

# on:
#   release:
#     types: [published]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Post-process
      run: |
        strip target/release/pipeswitchd
        mv target/release/pipeswitchd pipeswitchd
        zip pipeswitchd.zip pipeswitchd
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pipeswitchd.zip
        path: pipeswitchd.zip
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: pipeswitchd.zip